### ISSUE TITLE
Using rang with {fmt}

### ISSUE THREAD

**Issue by lefticus** [agauniyal/rang#104]
Similar to issue #93 I'm wondering if there's a way to effectively use rang with [{fmt}](https://github.com/fmtlib/fmt).

Assuming no one has any specific suggestions I'll probably try sorting out what adapter options there might be for it, short of writing to `std::stringstream` and sending that to {fmt}.

**Comment by agauniyal** [comment]
Rang operates in 2 modes - 1. Linux + Windows 10 2. Older Windows. The problem is with older windows where it actually calls some functions instead of sending terminal sequences(text code) to stdout/stderr etc. So I don't think current design will work with printf/{fmt} anyways...

**Comment by lefticus** [comment]
I actually think now that I've spent time playing with this, that this feature doesn't make any sense.

Taking into account what you said, plus just practically speaking:

```cpp
std::cout << rang::green << fmt::format("Hello: {}, name) << '\n';
```

Works just fine.

**Comment by agauniyal** [comment]
yeah PR would be great addition @lefticus :+1:

**Comment by DBJDBJ** [comment]
#include <stdio.h>
          #define RED "\x1b[31m"
          #define RESET "\x1b[0m"
 
         int main (int argc, char **argv)
         {
                 fmt::format(RED "Red {}" RESET "\n", "Face");
                return 0;
         }

**Comment by data-man** [comment]
IMO, can be closed.
Latest fmt already supports colors and styles.
See screenshots on [releases](https://github.com/fmtlib/fmt/releases).
