### ISSUE TITLE
Does not work in Ubuntu

### ISSUE THREAD

**Issue by Bhupesh-V** [agauniyal/rang#114]
Colours are not displayed

![error](https://user-images.githubusercontent.com/34342551/54428398-68508880-4743-11e9-80f3-454cb948964f.png)

**Comment by zethon** [comment]
Works fine for me on 18.04

![image](https://user-images.githubusercontent.com/5203583/56315143-f645d780-6124-11e9-9177-6ed3b0d6c439.png)

**Comment by agauniyal** [comment]
@Bhupesh-V check your $TERM env, the problem would be there most likely. I've rechecked it and it works fine so closing the issue. Feel free to leave a comment if it still doesn't works and I'll reopen and investigate.
