### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by zethon** [agauniyal/rang#121]
Is the code on `master` in a good state to be made into a new release? The [last release](https://github.com/agauniyal/rang/releases/tag/v3.1.0) is lacking the CMakeLists.txt file, so I'm forced to use `master` in my project when I pull this in. It'd be nice to have a release point to pull in instead.

**Comment by amirmasoudabdol** [comment]
I agree. There is a nice PR already merged for v4 with a very nice CMake file, and I really hope we get a new release with that.

**Comment by agauniyal** [comment]
@amirmasoudabdol I've imported that PR's change in https://github.com/agauniyal/rang/tree/new_cmake , is this all that needs to be done?
I'll release a minor version with those CMake files if it works for you.

**Comment by amirmasoudabdol** [comment]
Let me test this, and I will let you know! 🙂

**Comment by agauniyal** [comment]
@zethon v3.2 is out, thanks to @amirmasoudabdol.

**Comment by zethon** [comment]
Yay! Only 1.5 years later. :)
