### ISSUE TITLE
avoid multiple pointer copies

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/rang#14]
Current approach of capturing initial pointer to `cout`/`clog`/`cerr` buffer requires multiple copies since each .cpp file that'll include it will have their own copy.

But since the lib is using just 3 pointers within internal linkage, the overhead is almost negligible. But it can be resolved by providing static returns from function, see this **[stackoverflow question](http://stackoverflow.com/questions/39450809/avoiding-redefinition-of-variables-for-single-header)**.

**Comment by AxelStrem** [comment]
Is it a good idea to store the initial pointers at all? I can see it is done to prevent outputting color controlling sequences into file streams, but what if this is a desired behavior? e.g. the file is then streamlined back into the terminal, and user expects to see colors.
 Also introducing any kind of indirection like some temporary ostream buffer would break the coloring because of captured pointer mismatch. Same for user-implemented terminals, though this might be a bit far-fetched:)

**Comment by agauniyal** [comment]
@AxelStrem  I've discussed about it a couple of times and I'll still like that current behavior should be default behavior, so user doesn't needs to write the code himself. What we can do is to provide a custom stream manipulator like `std::hex`, which user can conditionally set to disable this default behavior and output color sequences even on non-tty interfaces like files.

Here's something to get started - 
- http://stackoverflow.com/questions/799599/c-custom-stream-manipulator-that-changes-next-item-on-stream
- http://stackoverflow.com/questions/13335193/sticky-custom-stream-manipulator

But with this approach, the pointer copies will still be there 😄 and this issue will need to get resolved as well. But for custom stream manipulators, you can open a new issue if you're willing to submit a PR with that :)

**Comment by AxelStrem** [comment]
@agauniyal Okay, after some consideration, it seems the proposed solution [obviously] won't work after all - as static variables are initialized upon the first function call, user can change rdbuf beforehand.

This either requires some explicit init() call from user, which in turn can provoke some order-of-initialization issues on user side, or introducing some global object - which is basically returning to square one.

**Comment by agauniyal** [comment]
@AxelStrem, Yes an init function would be needed but only if user tries to change `rdbuf`, so we could put a note - call `rang::init()` before changing the rdbuf of `cout`/`cerr`/`clog` or ignore this if you aren't changing it.

I also commented on the accepted answer about this problem but I guess it wasn't visible haha.

**Comment by AxelStrem** [comment]
@agauniyal I did see your comment, but I thought you were asking about the need to explicitly initialize in general, and the answer author thought the same since he denied that need.

Anyway, you want me to do it? I'll have to tweak your tests too though.

**Comment by AxelStrem** [comment]
I should also note that c++17 will provide **inline variables** that seem to be startup-initialized, so maybe it would be a better idea to wait for them instead, and to leave the interface as it is for now, with no intrusive `init()` calls.
