### ISSUE TITLE
no windows < 10 support

### ISSUE THREAD

**Issue by datgame** [agauniyal/rang#2]
just making this issue so i can be notified when there is support :)

**Comment by agauniyal** [comment]
I'll try to add support for windows by this week. Btw you'll be glad to know that if you include `<windows.h>` and probably `<io.h>` header files instead of `<unistd.h>`, the current solution works fine for windows 10 :smile:

**Comment by agauniyal** [comment]
```
#ifndef RANG_DOT_HPP
#define RANG_DOT_HPP

#if defined(__unix__) || defined(__unix) || defined(__linux__)
#define OS_LINUX
#elif defined(WIN32) || defined(_WIN32) || defined(_WIN64)
#define OS_WIN
#elif defined(__APPLE__) || defined(__MACH__)
#define OS_MAC
#else
#error Unknown Platform
#endif

#if defined(OS_LINUX) || defined(OS_MAC)
#include <unistd.h>
#elif defined(OS_WIN)
#include <io.h>
#endif

#include <iostream>
#include <cstdlib>
#include <iterator>
#include <algorithm>
#include <type_traits>

std::streambuf const *RANG_coutbuf = std::cout.rdbuf();
std::streambuf const *RANG_cerrbuf = std::cerr.rdbuf();
std::streambuf const *RANG_clogbuf = std::clog.rdbuf();

namespace rang {

	enum class style {
		reset = 0,
		bold = 1,
		dim = 2,
		italic = 3,
		underline = 4,
		blink = 5,
		reversed = 6,
		conceal = 7,
		crossed = 8
	};

	enum class fg {
		black = 30,
		red = 31,
		green = 32,
		yellow = 33,
		blue = 34,
		magenta = 35,
		cyan = 36,
		gray = 37
	};

	enum class bg {
		black = 40,
		red = 41,
		green = 42,
		yellow = 43,
		blue = 44,
		magenta = 45,
		cyan = 46,
		gray = 47
	};

	enum class fgB {
		black = 90,
		red = 91,
		green = 92,
		yellow = 93,
		blue = 94,
		magenta = 95,
		cyan = 96,
		gray = 97
	};

	enum class bgB {
		black = 100,
		red = 101,
		green = 102,
		yellow = 103,
		blue = 104,
		magenta = 105,
		cyan = 106,
		gray = 107
	};

	inline bool supportsColor()
	{
#if defined(OS_LINUX) || defined(OS_MAC)
		const std::string Terms[] = { "ansi",  "color",   "console", "cygwin",
			"gnome", "konsole", "kterm",   "linux",
			"msys",  "putty",   "rxvt",    "screen",
			"vt100", "xterm" };

		const char *env_p = std::getenv("TERM");
		if (env_p == nullptr) {
			return false;
		}

		std::string env_string(env_p);
		static const bool result = std::any_of(
			std::begin(Terms), std::end(Terms), [&](std::string term) {
			return env_string.find(term) != std::string::npos;
		});

#elif defined(OS_WIN)
		static const bool result = true;
#endif

		return result;
	}

	inline bool isTerminal(const std::streambuf *osbuf)
	{
		if (osbuf == RANG_coutbuf) {
#if defined(OS_LINUX) || defined(OS_MAC)
			return isatty(fileno(stdout)) ? true : false;
#elif defined(OS_WIN)
			return _isatty(_fileno(stdout)) ? true : false;
#endif
		}
		if (osbuf == RANG_cerrbuf || osbuf == RANG_clogbuf) {
#if defined(OS_LINUX) || defined(OS_MAC)
			return isatty(fileno(stderr)) ? true : false;
#elif defined(OS_WIN)
			return _isatty(_fileno(stderr)) ? true : false;
#endif
		}
		return false;
	}


	template <typename T>
	using enable = typename std::enable_if
		<
		std::is_same<T, rang::style>::value ||
		std::is_same<T, rang::fg>::value ||
		std::is_same<T, rang::bg>::value ||
		std::is_same<T, rang::fgB>::value ||
		std::is_same<T, rang::bgB>::value,
		std::ostream &
		>::type;

	template <typename T>
	inline enable<T> operator<<(std::ostream &os, T const value)
	{
		std::streambuf const *osbuf = os.rdbuf();
		return ((supportsColor()) && (isTerminal(osbuf)))
			? os << "\033[" << static_cast<int>(value) << "m"
			: os;
	}
}

#undef OS_LINUX
#undef OS_WIN
#undef OS_MAC

#endif /* ifndef RANG_DOT_HPP */
```

**Comment by agauniyal** [comment]
I've tested the latest commit on windows 10 - visual c++ compiler and everything works as intended :smile:

**Comment by agauniyal** [comment]
I've made something that works but it's bit of ugly for now. I've my semester exams and will work on it after they end.

**Comment by dileepsankhla** [comment]
I tried your windows version of header file rang.hppon windows 8.1 using visual C++ compiler (IDE: Visual Studio 12.0) and this was the output for the source code visualTest.cpp:

←[0m←[42m←[37mIf you're seeing green bg, then rang works!←[0m

I will be glad to contribute in this project for developing this header only library for windows version.

**Comment by AxelStrem** [comment]
Can I do it? My original intention was to fix this as it pretty much prevents me from using the lib

**Comment by agauniyal** [comment]
Sure :) Here's another relevant comment you might find helpful - https://github.com/agauniyal/rang/issues/4#issuecomment-227485676

**Comment by agauniyal** [comment]
http://stackoverflow.com/questions/36543301/detecting-windows-10-version

**Comment by AxelStrem** [comment]
Oh yeah, I know how to do it, there are some points I'm unclear on though, namely
- The fix can (ironically) conflict with issue #19 proposition: on Windows after user sets stream manipulator to write "colors" to non-tty stream, coloring will still affect console instead. No idea how to prevent that yet.
- Is it smart to dynamically detect windows version? Wouldn't it be better to just drop stream injections altogether and just use `SetConsoleTextAttribute` for Windows in general?

Also new CI tool will probably be required for this (appveyor?) and I'm not sure how it complies with tests

**Comment by agauniyal** [comment]
@AxelStrem -

I'm not sure if I'm aware of the problem you mentioned in point 1. Could you explain it a little bit?

About 2nd point, yes we could replace it with `SetConsoleTextAttribute` but I'm sure the next version of windows are not going to drop support for vt100 styled escaped codes soon since they recently started shipping it, but I cannot say that for `SetConsoleTextAttribute`.
Also there is a bash on windows thing too and many developers I know already use [cmder](http://cmder.net/) or mingw/git/cygwin inspired terminal instead of plain cmd or powershell). And `SetConsoleTextAttribute` isn't fully compatible with our current approach too, lots of markup would differ I guess. So I'm a little biased towards keeping the same approach for win10 + Linux and different for earlier windows versions, if it's possible. But let's make it a collaborative decision that we both take together and put some more time and thoughts into it 😄 

For appveyor, here's something I did a while ago - https://github.com/agauniyal/cs-iv-algorithm/blob/master/appveyor.yml

**Comment by AxelStrem** [comment]
Did it your way, tested locally so far, seems to work

**Comment by agauniyal** [comment]
@AxelStrem do you mind if I add you as a collaborator?

**Comment by agauniyal** [comment]
This is completed btw, thanks to @AxelStrem :D
