### ISSUE TITLE
write allColors test for testing library output visually

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/rang#27]
Would contain all possible color, background and style outputs from the library and will use `rang::forceColor` by default.

**Comment by n1zzo** [comment]
I can do this, do you want some particular test pattern to be generated?

**Comment by agauniyal** [comment]
Nothing fancy just some text that represents the color separated by new lines eg - 

```
This text color should be green.
This text color should be blue.
This text color should be red.
...
...
This text background color should be green.
This text background color should be red.
...
...
This text should be bold.
This text should be underlined.
...

and all other conditions...
```
Set of conditions from the code - 
```cpp
enum class style {
	reset     = 0,
	bold      = 1,
	dim       = 2,
	italic    = 3,
	underline = 4,
	blink     = 5,
	reversed  = 6,
	conceal   = 7,
	crossed   = 8
};

enum class fg {
	black   = 30,
	red     = 31,
	green   = 32,
	yellow  = 33,
	blue    = 34,
	magenta = 35,
	cyan    = 36,
	gray    = 37
};

enum class bg {
	black   = 40,
	red     = 41,
	green   = 42,
	yellow  = 43,
	blue    = 44,
	magenta = 45,
	cyan    = 46,
	gray    = 47
};

enum class fgB {
	black   = 90,
	red     = 91,
	green   = 92,
	yellow  = 93,
	blue    = 94,
	magenta = 95,
	cyan    = 96,
	gray    = 97
};

enum class bgB {
	black   = 100,
	red     = 101,
	green   = 102,
	yellow  = 103,
	blue    = 104,
	magenta = 105,
	cyan    = 106,
	gray    = 107
};
```

 Use them as `rang::<enum class name>::<style type>` eg - `rang::fg::green`. Just make sure the text is visible in every case ie. don't keep bg and fg same. Some styles might not work on Linux or Windows or both but that's okay. Here's how a simple test is written - https://github.com/agauniyal/rang/blob/develop/test/visualTest.cpp

Make sure you open a PR against develop branch and not the master branch since develop has latest changes. Feel free to ask any questions :smile:

**Comment by zeokav** [comment]
Hi again! Is this issue still up for grabs?
Also, is there a way we can iterate through all these or we going to have to brute force and write all the tests manually?

**Comment by agauniyal** [comment]
The user hasn't submitted anything yet, so yes it is 👍. And yes, we'll have to write all tests manually here since we need to produce same code as someone else might write, though we've to capture every case. But you can use some text editor with multiple cursors to make this easier 😄

**Comment by zeokav** [comment]
Alright. I'm gonna do this today. 👍

**Comment by n1zzo** [comment]
Sorry, I've been a little busy these days.
I give you the issue!

**Comment by agauniyal** [comment]
completed by @zeokav 👍
