### ISSUE TITLE
add windows gif to Readme

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/rang#31]
Just like the existing Linux gif present in Readme. Make sure to open PR against [develop](https://github.com/agauniyal/rang/tree/develop) branch and not the master branch.

**Comment by raj-maurya** [comment]
Hi @agauniyal ,

I would like to work on this issue #31.

**Comment by agauniyal** [comment]
@raj-maurya You're free to take any issue, however it would be helpful if you wait-for/complete  issue #27 before this so that your gif contains different cases to be showcased. Or you could write your own code to demonstrate :smile:

**Comment by agauniyal** [comment]
@raj-maurya the new allColors test has been pushed to develop branch so you can create a windows gif if you wish to 😄

**Comment by AxelStrem** [comment]
will this one do?
![rang-win](https://cloud.githubusercontent.com/assets/11349690/19836886/8134975e-9ebe-11e6-9ee4-c4657784ff3b.gif)

**Comment by agauniyal** [comment]
Wow, that was fantastic, how did you manage to code this example? Is it windows specific? And yes, this gif is sufficient for README.md 😄 👍

**Comment by AxelStrem** [comment]
@agauniyal it's actually pretty cross-platform(ish), thanks to rang :smile:
I only used windows-specific `Sleep()`. I also created a small game using only rang as graphics, great times lol - https://www.youtube.com/watch?v=WiAYsS6A8RI

**Comment by agauniyal** [comment]
@AxelStrem That's really cool 🎆 , about using sleep you can also use - http://en.cppreference.com/w/cpp/thread/sleep_for which is again cross-platform 😄 . Would love to see source for your games, animations and other stuff!

**Comment by AxelStrem** [comment]
oh yeah, this is actually a really good thought, my brain kinda defaults to `Sleep()` when I'm coding something small, a bad habit from 2003 I guess :D
