### ISSUE TITLE
No Windows 10 Support

### ISSUE THREAD

**Issue by ShyamW** [agauniyal/rang#32]

**Comment by ShyamW** [comment]
no support on windows 10, got working in compatibility mode with windows 7

**Comment by agauniyal** [comment]
What do you mean by no support for windows 10? This library works fine on windows 10, I've personally tested when I had a windows 10 system. Can you be more specific?

**Comment by AxelStrem** [comment]
Also how can it work in compatibility mode with Win 7 when master branch explicitly does not support Win 7 :laughing:

**Comment by agauniyal** [comment]
@ShyamW can you confirm it again? One of my friend reports library working fine on windows 10 system. Otherwise I'm going to close this issue.

**Comment by agauniyal** [comment]
Please reopen this issue if you find this problem under reproducible environments and I'll be glad to help 😄
