### ISSUE TITLE
adding the support of rang on windows

### ISSUE THREAD

**Issue by yahiafarghaly** [agauniyal/rang#40]
i started working on your code of the rang for the windows platform, for now i achieved the text color only
and will do the remaining in another time.
there is a lots of differences for color/styles codes on windows unlike UNIX systems.

currently i compiled and tested the code with visual studio community c++ 2015 but not added the project 
files of visual studio in my repo yet as i will try to make a cmake for generating the visual studio *.sln file on windows.

this is my first try
![image](https://cloud.githubusercontent.com/assets/8182964/20450148/dac53e8a-adf6-11e6-9ff5-46206ccdf6a3.png)

**Comment by agauniyal** [comment]
Hi 😄 , glad to see you've worked on this issue but I would like to remind you that someone has already ported the code to windows. The latest code is visible in [develop](https://github.com/agauniyal/rang/tree/develop) branch of this repo. I will be releasing v2 of rang with windows support soon. Thankyou for your interest :)
