### ISSUE TITLE
Informational: plumbum.colors

### ISSUE THREAD

**Issue by henryiii** [agauniyal/rang#59]
FYI: 
If you'd like to take a look at the Python library I wrote for color manipulation, its docs are [here](http://plumbum.readthedocs.io/en/latest/colors.html). The design docs are [here](http://plumbum.readthedocs.io/en/latest/colorlib.html). While it very much a python library, it might be useful for ideas. The `atexit` I believe has a analog in C and C++ -- Probably not useful for the library itself, but would be handy in the examples page. I handle the color choice between 24bit, 256, 16, and 8 rather poorly.

Thanks for the library!

Edit:

```cpp
std::atexit([](){std::cout << rang::style::reset;});
```

Should work unless a segfault is thrown.

**Comment by agauniyal** [comment]
Thankyou, I'll take a look at your lib and also improve the examples. I'm a bit busy atm but this library is going to get some features/updates pretty soon.
