### ISSUE TITLE
CMakeLists.txt removed? 

### ISSUE THREAD

**Issue by zethon** [agauniyal/rang#91]
I've been using this project for a while and just recently updated my repo to 3.1.0 only to find that CMakeLists.txt was removed in 9dd62bad5be09276902b7cb09a6d4c68276587bd.

Is there any reason the file was actually removed? It's not a huge problem but even if your CI is not using it, it would still be nice to have for those of us using CMake.

**Comment by agauniyal** [comment]
@zethon I'm not uptodate with cmake so was under worry that I might be breaking something. However I'll accept a PR if you want to add it to this repo :)

**Comment by zethon** [comment]
How would you feel about a minimal CMake file just so that it's easy to include this project in CMake-based projects? In other words, nothing that builds the tests, just something that sets up the proper includes?
