### ISSUE TITLE
Find bug using Background colors.

### ISSUE THREAD

**Issue by quietash9704** [agauniyal/rang#97]
Hello, developer.
I send pull request that helps other testers use your programs.

But, while I test that, find bug using Background colors.

When I do 'bg::reset' before 'endl', that works well. Show the url.
`cout << bg::red << "------Select Menu------" << bg::reset << endl;`
https://imgur.com/a/KPBlEE5

But, when I do 'bg::reset' after 'endl', that makes problems. Show the url.
`cout << bg::red << "------Select Menu------" << endl << bg::reset ;`
https://imgur.com/a/oVYMBnv

I want to know why this problem happened.

**Comment by agauniyal** [comment]
It's because endl means a newline so you're asking rang to -
1. Set bg as red
2. Output a new line still with bg red
3. Reset bg to normal

hence the wrong image behavior. The fix is exactly what you've done ie reset bg before endl.

**Comment by HemilTheRebel** [comment]
This issue should be closed
